Improved TypeScript support
colorfy-software/react-native-modalfy pull request #114
Opened 2023-05-30 15:54 UTC by v-honcharenko

Added the ability to extend the default `ModalfyParams` with a custom declaration for better DX. 
It doesn't make any breaking changes and should work as before if `ModalfyCustomParams` interface is not overwritten.

Example:

1. Declare your own ModalStackParams type:
```ts
// modal.types.ts
export type ModalStackParams = {
  dialog: { title: string };
};
```

2. In the file `react-native-modalfy.d.ts` (or in the any other place when the `createModalStack` is called), add:
```ts
import 'react-native-modalfy';
import type { ModalStackParams } '/path/to/modal.types';

declare module 'react-native-modalfy' {
  interface ModalfyCustomParams extends ModalStackParams {}
}
```

3. Get full support of types out of the box:
```diff
const MyComponent = () => {
  // no need to manually pass declared ModalStackParams 👇
-  const { openModal } = useModal<ModalStackParams>();
+  const { openModal } = useModal();

  const openDialog = () => {
    // types still work well here 👇
    openModal('dialog', { title: 'Title' });
  };
  // ...
}
```

2023-06-12 08:47 UTC, CharlesMangwa commented
amazing change @v-honcharenkom, thanks a lot for the pr! could you also update the `/example` to reflect the modifications pls?

2023-06-12 08:49 UTC, CharlesMangwa requested changes
amazing change @v-honcharenko, thanks a lot for the pr! could you also update the /example to reflect the modifications pls?

2023-06-18 01:04 UTC, v-honcharenko commented
@CharlesMangwa I've updated the PR, please, review it.

2023-06-20 11:20 UTC, CharlesMangwa approved these changes
pr looking great, thanks for the changes! i also [updated  the documentation](https://colorfy-software.gitbook.io/react-native-modalfy/guides/typing#optional-provisioning-of-params-generic) to reflect the new state of ts support 🥳 . feel free to let me know if there's something i should change!

2023-06-20 11:21 UTC, merged